include: "https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml"

.vars-devel:
  variables:
    MANIFEST_PATH: "app.drey.Synchrony.Devel.json"
    FLATPAK_MODULE: "synchrony"
    APP_ID: "app.drey.Synchrony.Devel"
    RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
    BUNDLE: "app.drey.Synchrony.Devel.flatpak"
  before_script:
    - flatpak --user install -y org.freedesktop.Sdk.Extension.golang

flatpak@x86_64:
  extends: [".flatpak@x86_64", ".vars-devel"]

flatpak@aarch64:
  extends: [".flatpak@aarch64", ".vars-devel"]

nightly@x86_64:
  extends: ".publish_nightly"
  needs: ["flatpak@x86_64"]

nightly@aarch64:
  extends: ".publish_nightly"
  needs: ["flatpak@aarch64"]
